Add files via upload
Nexa-Radiant-Lab/Daemon_Server pull request #5
Opened 2024-09-22 21:21 UTC by Romeo509

2024-09-22 21:28 UTC, Romeo509 commented
Implement ContentGuard class for AI-based content analysis

2024-09-22 21:28 UTC, Romeo509 commented
Implement ContentGuard class for AI-based content analysis

2024-09-23 06:16 UTC, abdiaelema76 commented on components/ai_agents/content_guard.py
> +    def analyze_content(self, prompt):
Please add an error handling block in the analyze_content method to handle potential failures from the ollama.generate call.

2024-09-23 06:17 UTC, abdiaelema76 approved these changes

2024-09-23 07:56 UTC, Daniel-Azil reviewed
I love that fact that you added a well written doc string. Again, that's neat.
Elema made mention of error handling. looking out for the errors you need to consider about 3 different cases,

1. **ollama package being corrupted or outdated:** I've worked with ollama on my terminal, the package sometimes doesn't work how it suppose to after not being utilised for a long time. it could be due to outdated version.
2. **Corrupted Package:** Due to the fact that you tried installing the package even after it's already installed. 
Ollama doesn't have a check for knowing if the package installed and it's in it latest version. If you decide to run the install command again, it rather reinstalls the package from scratch and if you decide cancel the installation, and use ollama, everything breaks!
3. **There are no model's to access**
4. **Prompt is too too long**

- Simple use try and except to handle these errors gracefully all at once. I'll work on resolving other issues like large prompts.

2024-09-23 08:54 UTC, Daniel-Azil requested changes

2024-09-23 08:54 UTC, Daniel-Azil commented on components/ai_agents/content_guard.py
> +class ContentGuard:
Create an init method in the class to pass the **task,** and **content** objects as attributes, assigning them to **self.task,**  and **self.content** within the init method.

The rest of you code will need to be consistent with the attributes.

2024-09-23 08:54 UTC, Daniel-Azil commented on components/ai_agents/content_guard.py
> +        prompt = task.strip() + "\n" + content.strip()
Use an **if** statement to check if task and content object contains the value it needs to have.

when the content is retrieved from the webscraping operation, there are no guarantee that the content is present. so we have to check just in case. Put in an **else** block for content to tell us the content is not available for the real scenerio when integrating the web crawling.

2024-09-25 17:29 UTC, closed without merging